In [3]:
import pandas as pd

In [ ]:
df_main = pd.read_csv("datasets/New International_Education_Costs.csv")
df_main

In [42]:
check = df_main.sort_values(by=['Country']).tail(20)
check

,Country,City,University,Program,Level,Duration_Years,Tuition_USD,Living_Cost_Index,Rent_USD,Visa_Fee_USD,Insurance_USD,Exchange_Rate
227,USA,Columbus,Ohio State University,Computer Science,Bachelor,4.0,32800,71.4,1400,160,1500,1.0
228,USA,West Lafayette,Purdue University,Computer Science,Bachelor,4.0,31500,68.9,1300,160,1500,1.0
233,USA,Corvallis,Oregon State University,Computer Science,Bachelor,4.0,26500,70.1,1300,160,1500,1.0
232,USA,College Station,Texas A&M University,Computer Science,Bachelor,4.0,27000,69.5,1300,160,1500,1.0
825,Ukraine,Kharkiv,Kharkiv Polytechnic,Data Science,Master,2.0,3400,42.5,330,120,300,36.8
841,Ukraine,Dnipro,Dnipro Polytechnic,Data Analytics,Master,2.0,3300,40.5,300,120,300,36.8
817,Ukraine,Lviv,Lviv Polytechnic,Computer Science,Master,2.0,3500,43.2,350,120,300,36.8
809,Ukraine,Kyiv,Igor Sikorsky Kyiv Polytechnic,Software Engineering,Bachelor,4.0,3800,45.8,400,120,300,36.8
833,Ukraine,Odesa,Odesa Polytechnic,Artificial Intelligence,PhD,4.0,3600,41.8,320,120,300,36.8
794,Uruguay,Rivera,UTEC,Information Systems,Bachelor,4.0,0,47.8,350,90,350,39.5
778,Uruguay,Salto,Universidad ORT Uruguay,Computer Science,Master,2.0,6500,48.5,380,90,350,39.5
786,Uruguay,Maldonado,Universidad Catolica,Data Science,Master,2.0,7000,49.2,400,90,350,39.5
770,Uruguay,Montevideo,Universidad de la Republica,Computer Engineering,PhD,4.0,0,52.4,450,90,350,39.5
802,Uruguay,Paysandu,Universidad de Paysandu,Software Engineering,Master,2.0,0,46.5,330,90,350,39.5
829,Uzbekistan,Bukhara,Bukhara State University,Computer Science,Bachelor,4.0,3500,39.8,220,160,250,12300.0
821,Uzbekistan,Samarkand,Samarkand State University,Data Analytics,Master,2.0,3800,41.2,250,160,250,12300.0
845,Uzbekistan,Andijan,Andijan State University,Software Development,Master,2.0,3200,37.8,180,160,250,12300.0
813,Uzbekistan,Tashkent,INHA University Tashkent,Computer Science,Bachelor,4.0,4200,44.5,300,160,250,12300.0
837,Uzbekistan,Namangan,Namangan Institute,Information Technology,Master,2.0,3400,38.5,200,160,250,12300.0
140,Vietnam,Ho Chi Minh City,HCMUT,Software Engineering,Bachelor,4.0,3200,43.6,450,120,250,24450.0

In [40]:
grouping = df_main.groupby('Country').size().sort_values(ascending=False)
grouping

Country
UK              93
Australia       86
USA             78
Canada          76
Germany         33
                ..
Hong Kong        1
Nigeria          1
South Africa     1
Taiwan           1
Vietnam          1
Length: 71, dtype: int64

In [25]:
Harvard = df_main.University.map(lambda desc: "Harvard" in desc).sum()
Stanford = df_main.University.map(lambda desc: "Stanford" in desc).sum()

dataframe = pd.DataFrame({'Harvard': [Harvard],
                          'Stanford': [Stanford],})
dataframe

   Harvard  Stanford
0        2         5

In [68]:
check_countCountry = df_main.Country.value_counts()
check_countCountry

Country
UK                93
Australia         86
USA               78
Canada            76
Germany           33
                  ..
Czech Republic     1
Hong Kong          1
Israel             1
Nigeria            1
Vietnam            1
Name: count, Length: 71, dtype: int64

In [31]:
df_main.iloc[0]

Country                             USA
City                          Cambridge
University           Harvard University
Program                Computer Science
Level                            Master
Duration_Years                      2.0
Tuition_USD                       55400
Living_Cost_Index                  83.5
Rent_USD                           2200
Visa_Fee_USD                        160
Insurance_USD                      1500
Exchange_Rate                       1.0
Name: 0, dtype: object

In [64]:
sort_USA = df_main[df_main['Country'] == 'USA'].groupby(['Country', 'University']).Tuition_USD.agg(['min', 'max'])
sort_USA

                                                   min    max
Country University
USA     Arizona State University                 28000  41200
        Carnegie Mellon                          51200  56000
        Columbia University                      52800  62000
        Cornell University                       49800  49800
        Duke University                          51500  51500
        Georgia Tech                             33500  48000
        Harvard University                       55400  58000
        Johns Hopkins                            53600  53600
        MIT                                      53800  58000
        NC State University                      27500  47000
        Northeastern University                  54000  54000
        Ohio State University                    32800  32800
        Oregon State University                  26500  26500
        Portland State University                45000  45000
        Princeton University                     54000  54000
        Purdue University                        31500  31500
        Stanford University                      52000  57000
        Texas A&M University                     27000  27000
        UC Berkeley                              43500  54000
        UC Berkeley Extension                    52000  52000
        UC Davis                                 42800  48000
        UC San Diego                             44200  49000
        UCLA                                     43000  52000
        UIUC                                     45800  45800
        UT Austin                                40900  49000
        University of Chicago                    52400  58000
        University of Colorado                   39800  39800
        University of Denver                     47000  47000
        University of Florida                    28500  28500
        University of Illinois Urbana-Champaign  36800  36800
        University of Michigan                   52000  52300
        University of Minnesota                  42500  48000
        University of Pennsylvania               51900  53500
        University of Texas Austin               40500  40500
        University of Washington                 38900  51000
        University of Wisconsin                  38200  38200
        University of Wisconsin-Madison          37500  37500
        Vanderbilt University                    50800  50800
        Yale University                          54500  54500

In [66]:
sum_USA = df_main[df_main['Country'] == 'USA'].sum()
sum_USA

Country              USAUSAUSAUSAUSAUSAUSAUSAUSAUSAUSAUSAUSAUSAUSAU...
City                 CambridgeAnn ArborAtlantaAustinStanfordBostonS...
University           Harvard UniversityUniversity of MichiganGeorgi...
Program              Computer ScienceAerospace EngineeringIndustria...
Level                MasterBachelorBachelorBachelorPhDPhDBachelorMa...
Duration_Years                                                   264.0
Tuition_USD                                                    3723900
Living_Cost_Index                                               6068.1
Rent_USD                                                        145000
Visa_Fee_USD                                                     12480
Insurance_USD                                                   117000
Exchange_Rate                                                     78.0
dtype: object

In [ ]:
df_typo = df_main.loc[df_main['University'] == 'Massachusetts', 'University'] = 'MIT'

'MIT'